# Generated by Django 5.1.6 on 2025-03-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='formacomunicacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
