# Generated by Django 5.1.6 on 2025-03-06 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofrade', '0002_alter_estado_nombre_alter_formacomunicacion_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriahermano',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditoriahermano',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('ELIMINAR', 'Eliminar'), ('PAGO', 'Registro de Pago'), ('CAMBIO_ESTADO', 'Cambio de Estado')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('evento', 'Evento'), ('pago', 'Pago'), ('tarea', 'Tarea'), ('general', 'General')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_evento', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
