# Generated by Django 5.1.6 on 2025-03-07 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofrade', '0004_alter_notificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_cofrade.hermano'),
        ),
    ]
