# Generated by Django 5.1.6 on 2025-03-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofrade', '0005_alter_notificacion_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
