# Generated by Django 5.1.6 on 2025-03-07 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofrade', '0006_delete_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('cofradia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cofrade.cofradia')),
            ],
        ),
    ]
