# Generated by Django 5.1.6 on 2025-03-07 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofrade', '0007_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('estado_material', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('fianza', models.CharField(max_length=100)),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cofrade.hermano')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cofrade.inventario')),
            ],
        ),
    ]
