# Generated by Django 5.1.6 on 2025-03-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofrade', '0008_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermano',
            name='numero_hermano',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
