# Generated by Django 5.1.6 on 2025-03-07 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofrade', '0010_alter_hermano_numero_hermano'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriahermano',
            name='identificador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='identificador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finanza',
            name='identificador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='identificador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='identificador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='identificador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='identificador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='numero_hermano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField(blank=True, null=True)),
                ('donante', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cofradia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cofrade.cofradia')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_cofrade.evento')),
            ],
        ),
    ]
