# Generated by Django 5.1.6 on 2025-03-07 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofrade', '0011_auditoriahermano_identificador_evento_identificador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriahermano',
            name='cofradia',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cofrade.cofradia'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='cofradia',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cofrade.cofradia'),
        ),
    ]
