# Generated by Django 5.1.6 on 2025-03-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofrade', '0012_auditoriahermano_cofradia_prestamo_cofradia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
