# Generated by Django 5.1.6 on 2025-03-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofrade', '0013_alter_donacion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='cantidad_total',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
