# Generated by Django 5.2.3 on 2025-09-01 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cofradia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('historia', models.TextField(blank=True, help_text='Texto largo con la historia de la cofradía para web pública', null=True)),
                ('imagen_principal', models.ImageField(blank=True, help_text='Foto destacada', null=True, upload_to='cofradia/')),
            ],
            options={
                'verbose_name_plural': 'Cofradías',
            },
        ),
        migrations.CreateModel(
            name='EstadoHermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado del Hermano',
                'verbose_name_plural': 'Estados de los Hermanos',
            },
        ),
        migrations.CreateModel(
            name='FormaComunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Formas de Comunicación',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Formas de Pago',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('anual', 'Anual'), ('extraordinaria', 'Extraordinaria')], db_index=True, max_length=20)),
                ('anio', models.PositiveIntegerField(db_index=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('cofradia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='gestion_cofradia.cofradia')),
            ],
            options={
                'verbose_name_plural': 'Cuotas',
                'ordering': ['-anio', 'tipo'],
                'unique_together': {('cofradia', 'tipo', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to='documentos/', verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Subida')),
                ('visibilidad', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='privado', max_length=10, verbose_name='Visibilidad')),
                ('cofradia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cofradia.cofradia')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Enser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(db_index=True, max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('identificador', models.CharField(db_index=True, help_text='Código único para identificar el enser (ejemplo: nº inventario)', max_length=50, unique=True)),
                ('cofradia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensers', to='gestion_cofradia.cofradia')),
            ],
            options={
                'verbose_name_plural': 'Enseres',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(db_index=True)),
                ('lugar', models.CharField(blank=True, max_length=150, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('es_interno', models.BooleanField(default=False)),
                ('notificar', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('reunion', 'Reunión'), ('culto', 'Culto'), ('misa', 'Misa'), ('procesion', 'Procesión')], default='reunion', max_length=20)),
                ('cofradia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='gestion_cofradia.cofradia')),
                ('cuota_extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cofradia.cuota')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Hermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_hermano', models.PositiveIntegerField(db_index=True, help_text='Número interno único dentro de la cofradía')),
                ('dni', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('apellidos', models.CharField(db_index=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_inicio_cofradia', models.IntegerField(blank=True, null=True)),
                ('fecha_ultimo_pago', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lopd', models.FileField(blank=True, null=True, upload_to='lopd_files/')),
                ('rol', models.CharField(choices=[('costalero', 'Costalero'), ('mantilla', 'Mantilla'), ('nazareno', 'Nazareno'), ('insignia', 'Insignia'), ('hermano', 'Hermano')], default='hermano', max_length=20)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('cofradia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hermanos', to='gestion_cofradia.cofradia')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hermanos', to='gestion_cofradia.estadohermano')),
                ('forma_comunicacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_cofradia.formacomunicacion')),
                ('forma_pago', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_cofradia.formapago')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario asociado para portal hermano', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hermanos',
            },
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(db_index=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('fianza', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('prestado', 'Prestado'), ('devuelto', 'Devuelto')], default='solicitado', max_length=20)),
                ('cofradia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='gestion_cofradia.cofradia')),
                ('enser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='gestion_cofradia.enser')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cofradia.evento')),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='gestion_cofradia.hermano')),
            ],
            options={
                'verbose_name_plural': 'Alquileres',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('publico', models.BooleanField(default=True, help_text='Visible en web pública')),
                ('cofradia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='gestion_cofradia.cofradia')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_destinatarios', models.CharField(blank=True, help_text='Filtro para grupo de hermanos (ej: estado=activo, rol=nazareno)', max_length=255, null=True)),
                ('titulo', models.CharField(db_index=True, max_length=100)),
                ('cuerpo', models.TextField()),
                ('enviada', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('leida', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('cuota', 'Cuota'), ('evento', 'Evento'), ('general', 'General')], db_index=True, default='general', max_length=20)),
                ('cofradia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='gestion_cofradia.cofradia')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='gestion_cofradia.cuota')),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(db_index=True)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('domiciliacion', 'Domiciliación'), ('tarjeta', 'Tarjeta'), ('bizum', 'Bizum')], max_length=50)),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cofradia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion_cofradia.cofradia')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion_cofradia.cuota')),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion_cofradia.hermano')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('hermano', 'Hermano'), ('secretario', 'Secretario'), ('tesorero', 'Tesorero'), ('hermano_mayor', 'Hermano Mayor')], default='hermano', max_length=20)),
                ('cofradia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cofradia.cofradia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, db_index=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.AddIndex(
            model_name='hermano',
            index=models.Index(fields=['cofradia', 'num_hermano'], name='gestion_cof_cofradi_3e366d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hermano',
            unique_together={('cofradia', 'dni'), ('cofradia', 'num_hermano')},
        ),
    ]
