# Generated by Django 5.1.6 on 2025-02-26 11:57

import django.db.models.deletion
import django.db.models.query
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cofradia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('color', models.CharField(help_text='Código HEX del color (ej: #ff5733)', max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormaComunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_secretario', models.BooleanField(default=False)),
                ('cofradias', models.ManyToManyField(blank=True, to='gestion_cofradia.cofradia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_inicio', models.PositiveIntegerField(default=2025)),
                ('fecha_ultimo_pago', models.PositiveIntegerField(default=2025)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('iban', models.CharField(max_length=24, null=True)),
                ('cofradia', models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cofradia.cofradia')),
                ('estado', models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cofradia.estado')),
                ('forma_comunicacion', models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cofradia.formacomunicacion')),
                ('forma_pago', models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cofradia.formapago')),
                ('perfil_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_cofradia.perfilusuario')),
            ],
            options={
                'permissions': [('puede_ver_hermanos', 'Puede ver la lista de hermanos'), ('puede_crear_hermanos', 'Puede crear hermanos'), ('puede_editar_hermanos', 'Puede editar hermanos'), ('puede_eliminar_hermanos', 'Puede eliminar hermanos')],
            },
        ),
    ]
