# Generated by Django 5.2.3 on 2025-06-14 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofradia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='grupo_destinatarios',
            field=models.CharField(blank=True, help_text='Filtro para grupo de hermanos (ej: estado=activo, rol=nazareno)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='canal',
            field=models.ForeignKey(blank=True, help_text='Canal para notificaciones grupales', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_cofradia.formacomunicacion'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='gestion_cofradia.hermano'),
        ),
    ]
