# Generated by Django 5.2.3 on 2025-09-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofradia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='cofradia',
        ),
        migrations.RemoveField(
            model_name='alquiler',
            name='cofradia',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='cofradia',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='cofradia',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='cofradia',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cofradia',
        ),
        migrations.RemoveField(
            model_name='enser',
            name='cofradia',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='cofradia',
        ),
        migrations.RemoveIndex(
            model_name='hermano',
            name='gestion_cof_cofradi_3e366d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='hermano',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('tipo', 'anio')},
        ),
        migrations.AlterField(
            model_name='hermano',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='num_hermano',
            field=models.PositiveIntegerField(db_index=True, help_text='Número interno único', unique=True),
        ),
        migrations.RemoveField(
            model_name='hermano',
            name='cofradia',
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='cofradia',
        ),
        migrations.DeleteModel(
            name='Cofradia',
        ),
    ]
