# Generated by Django 5.2.3 on 2025-06-16 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofradia', '0002_notificacion_grupo_destinatarios_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alquiler',
            options={'verbose_name_plural': 'Alquileres'},
        ),
        migrations.AlterModelOptions(
            name='cofradia',
            options={'verbose_name_plural': 'Cofradías'},
        ),
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['-anio', 'tipo'], 'verbose_name_plural': 'Cuotas'},
        ),
        migrations.AlterModelOptions(
            name='enser',
            options={'verbose_name_plural': 'Enseres'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='formacomunicacion',
            options={'verbose_name_plural': 'Formas de Comunicación'},
        ),
        migrations.AlterModelOptions(
            name='formapago',
            options={'verbose_name_plural': 'Formas de Pago'},
        ),
        migrations.AlterModelOptions(
            name='hermano',
            options={'verbose_name_plural': 'Hermanos'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago'], 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'verbose_name_plural': 'Tareas'},
        ),
        migrations.RemoveField(
            model_name='hermano',
            name='ibam',
        ),
        migrations.AddField(
            model_name='hermano',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='fecha_entrega',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cofradia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cofradia',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cofradia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cofradia',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cofradia',
            name='nombre',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='cofradia',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='anio',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='tipo',
            field=models.CharField(choices=[('anual', 'Anual'), ('extraordinaria', 'Extraordinaria')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Subida'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='enser',
            name='identificador',
            field=models.CharField(db_index=True, help_text='Código único para identificar el enser (ejemplo: nº inventario)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='enser',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='enser',
            name='tipo',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='estadohermano',
            name='nombre',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='formacomunicacion',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='apellidos',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='fecha_inicio_cofradia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='forma_comunicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_cofradia.formacomunicacion'),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='forma_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_cofradia.formapago'),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='num_hermano',
            field=models.PositiveIntegerField(db_index=True, help_text='Número interno único dentro de la cofradía'),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
