# Generated by Django 5.2.3 on 2025-06-17 21:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofradia', '0004_alter_notificacion_destinatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='gestion_cofradia.cuota'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('cuota', 'Cuota'), ('evento', 'Evento'), ('general', 'General')], db_index=True, default='general', max_length=20),
        ),
    ]
