# Generated by Django 5.2.3 on 2025-06-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofradia', '0005_notificacion_cuota_notificacion_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='canal',
        ),
    ]
