# Generated by Django 5.2.3 on 2025-06-18 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofradia', '0006_remove_notificacion_canal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hermano',
            unique_together={('cofradia', 'dni'), ('cofradia', 'num_hermano')},
        ),
        migrations.AlterField(
            model_name='hermano',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario asociado para portal hermano', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
