# Generated by Django 5.1.6 on 2025-02-27 12:13

import django.db.models.deletion
import django.db.models.query
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cofradia', '0007_rename_apellido_hermano_apellidos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermano',
            name='cofradia',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cofradia.cofradia'),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='estado',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cofradia.estado'),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='forma_comunicacion',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cofradia.formacomunicacion'),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='forma_pago',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cofradia.formapago'),
        ),
        migrations.CreateModel(
            name='AuditoriaHermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('MODIFICAR', 'Modificar'), ('ELIMINAR', 'Eliminar')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hermano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cofradia.hermano')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
